### ISSUE TITLE
Register Current as a Release

### ISSUE THREAD

**Issue by Tickthokk** [jenssegers/blade#11]
I ran into an issue where `composer require jenssegers/blade` set it up to the `^1.0` version in my composer.json.  This isn't the newest stuff available, and I was missing out on the super nice addition of the `compiler()->directive` stuff (in `dev-master`).

Registering a new release in github could save others a headache I think.

Thanks for the tool!

**Comment by jenssegers** [comment]
The composer version constraints for Laravel should allow components up to Laravel 5.3 though.

**Comment by Tickthokk** [comment]
Apologies, but I think you misunderstood.

_Your_ release doesn't include everything.  Take a look at your `1.0.0` release, it's not the same as what's in your `master`.  Issuing a 1.0.1 release should fix this.

Ref: https://github.com/jenssegers/blade/releases

**Comment by jenssegers** [comment]
Wow you are right! Tagged a new release now.
