### ISSUE TITLE
Upgrade to Blade 5.5

### ISSUE THREAD

**Issue by connerbw** [jenssegers/blade#16]
New syntax:

```
@component, @slot
@verbatim
$loop variable
@stack
... etc ...
```

More info: https://laravel.com/docs/5.5/blade

**Comment by jenssegers** [comment]
You should be able to upgrade to 5.5 components with this package.

**Comment by connerbw** [comment]
```
"illuminate/view": "^5.5.0",
"jenssegers/blade": "^1.1"
```

Works for me.

**Comment by jenssegers** [comment]
Check https://semver.mwl.be/#?package=illuminate%2Fview&version=%5E5.1&minimum-stability=stable

**Comment by connerbw** [comment]
Very cool. Thank you for your help. You make great composer packages.
