### ISSUE TITLE
How to Minify output

### ISSUE THREAD

**Issue by ngangchill** [jenssegers/blade#2]
Laravel Blade: how to minify HTML/CSS/JS if i use your library??
any help will be great for me.

i have found a repository to use partials within blade template, will you give me any suggestion how can i use it with your library.

Repository Link:  https://github.com/crhayes/blade-partials

Thanks in advance..

**Comment by jenssegers** [comment]
You should check out how the service provider modifies the original blade: https://github.com/crhayes/blade-partials/blob/master/src/Crhayes/BladePartials/ViewServiceProvider.php
