### ISSUE TITLE
is it possible to use custom blade Blade::directive...

### ISSUE THREAD

**Issue by ngangchill** [jenssegers/blade#3]
is it possible to use custom blade Blade::directive() , if yes, will you give me an example??

**Comment by daison12006013** [comment]
@ngangchill, you can now call 

```$blade->compiler()->directive(<directive>, <callback>)```

check the test suite for more info.

**Comment by arhatal** [comment]
isn't work:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\View\Factory' does not have a method 'compiler' in /var/www/project/vendor/jenssegers/blade/src/Blade.php on line 79
and next
Fatal error: Uncaught Error: Call to a member function directive() on null in ...
