### ISSUE TITLE
undefined function asset() 

### ISSUE THREAD

**Issue by hoangnamitc** [jenssegers/blade#41]
hi,
I'm use
{{ asset('js/main.js') }}

but has error bellow:
![image](https://user-images.githubusercontent.com/7042462/67789468-9e5e3500-faa6-11e9-900f-12be0ce8a440.png)

**Comment by bat92** [comment]
"asset" is a function related to the laravel mix and does not apply to the blade template engine. You can use https://github.com/JeffreyWay/laravel-mix
