### ISSUE TITLE
x-component tag example

### ISSUE THREAD

**Issue by jreviews** [jenssegers/blade#49]
I put together a demo using this package that allows using the x-component tag syntax in template files.

https://github.com/clickfwd/blade-standalone-component-tags

Would love some feedback on whether this is a good approach or if someone has a better way to do it.

**Comment by jreviews** [comment]
Ok, I just realized this doesn't work with anonymous components. Those with just a view template file and no associated class. Does someone know how to get those working?

**Comment by ryangjchandler** [comment]
> 
> 
> Ok, I just realized this doesn't work with anonymous components. Those with just a view template file and no associated class. Does someone know how to get those working?

The same way that you create an alias for the class based components - instead of passing a class, pass the name of a view.

**Comment by jreviews** [comment]
@ryangjchandler Thanks, but do you have this working? I get the following error:

`GET / - Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Foundation\Application] is not instantiable. in /../blade/vendor/illuminate/container/Container.php:1011
`

This seems to be tightly coupled with the Laravel application in `ComponentTagCompiler`.

I did manage to get it working in the end, but not using the blade class in this repo.

I had to create a fake version of the Illuminate\Contracts\Foundation\Application class and pass that as the 3rd parameter to my own version of the `Blade implements FactoryContract` class and then map some classes in the container to make them load my versions.

It's all very convoluted, but everything works now.

**Comment by ryangjchandler** [comment]
Yeah, it's slightly annoying that it's tightly bound to the Laravel `Foundation\Application` class.

**Comment by lexdubyna** [comment]
@jreviews Could you please share your convoluted solution where everything works?

**Comment by jreviews** [comment]
@lexdubyna I don't have it anymore, but this repo has a working example https://github.com/clickfwd/yoyo-blade-app

You can see how to use it here https://github.com/clickfwd/yoyo-blade-app/blob/master/app/bootloader.php

Ignore all the Yoyo stuff and use $blade->render to render your layout.

**Comment by lexdubyna** [comment]
@jreviews  Thank you very much! Your solution works great!

**Comment by lexdubyna** [comment]
#57
