### ISSUE TITLE
Target class [filesystem] does not exist

### ISSUE THREAD

**Issue by topclaudy** [jenssegers/blade#50]
In Laravel 7.x, after calling `$blade->make`, any usage of the **Storage** facade generates the error "Target class [filesystem] does not exist".

**Comment by AjithLalps** [comment]
Why you need this package when you are using laravel?

**Comment by topclaudy** [comment]
@AjithLalps Thanks for the insight. The `view` helper does exactly what this package is doing outside of Laravel
