### ISSUE TITLE
你好, 请教一个关于laravel的 DB 基本用法迁移的问题

### ISSUE THREAD

**Issue by fizzcome** [jenssegers/blade#8]
如这里所说: http://stackoverflow.com/questions/27956821/can-i-use-dbtabletags-outside-of-laravel

网上有很多教程移植 Eloquent , 并且可以使用成功, 如移植到 codeigniter 中, 可以直接使用 Active Record 用法(User::first());

可是, 如何移植他的基本用法呢 ? 如: DB::table('user')->get();

**Comment by fizzcome** [comment]
sorry , the question is :  
can I get the basic usage of laravel's database, like `DB::table('user')->get()`, not the usage of `Active Record` like `User::first()`;  
here is the same question , but not effective:  [http://stackoverflow.com/questions/27956821/can-i-use-dbtabletags-outside-of-laravel](http://stackoverflow.com/questions/27956821/can-i-use-dbtabletags-outside-of-laravel)

**Comment by tristanrollet** [comment]
Try using this: https://github.com/mattstauffer/Torch

**Comment by fizzcome** [comment]
thank you
